version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  Hello-World:
    docker:
      - image: alpine:3.15
        auth:
          username: $MYDOCKER_HUB
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  Fetch-Code:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: $MYDOCKER_HUB
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Getting the Code
          command: |
            ls -al
            echo '^^^Your repo files^^^'
  Using-Node:
    docker:
      - image: cimg/node:17.2
        auth:
          username: $MYDOCKER_HUB
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v
  Now-Complete:
    docker:
      - image: alpine:3.15
        auth:
          username: $MYDOCKER_HUB
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'The work is now complete.'
  notify:
    docker:
      - image: cimg/base:stable
        auth:
          username: $MYDOCKER_HUB
          password: $DOCKERHUB_PASSWORD
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*congratulation, you got the slack message*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always 
workflows:
  Example-Workflow:
    jobs:
      - Hello-World
      - Fetch-Code:
          requires:
            - Hello-World
      - Using-Node:
          requires:
            - Fetch-Code
      - Hold-for-Approval:
          type: approval
          requires:
            - Using-Node
            - Fetch-Code
      - Now-Complete:
          requires:
            - Hold-for-Approval
      - notify:
          requires:
            - Now-Complete


          
            
