version: 2.1
orbs:
  slack: circleci/slack@4.9.3
  cypress: cypress-io/cypress@3.1.2

jobs:
  notify:
    docker:
      - image: cimg/base:stable
        auth:
          username: $MYDOCKER_HUB
          password: $DOCKERHUB_PASSWORD
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*congratulation, you got the slack message*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
workflows:
  Example-Workflow:
    jobs: 
      - cypress/run:
           Yarn: true
      - notify:
          requires:
            - cypress/run        

          
            
